package d2s

type item struct {
	Identified         uint64             `json:"identified"`
	Socketed           uint64             `json:"socketed"`
	New                uint64             `json:"new"`
	IsEar              uint64             `json:"is_ear"`
	StarterItem        uint64             `json:"starter_item"`
	SimpleItem         uint64             `json:"simple_item"`
	Ethereal           uint64             `json:"ethereal"`
	Personalized       uint64             `json:"personalized"`
	PersonalizedName   string             `json:"personalized_name,omitempty"`
	GivenRuneword      uint64             `json:"given_runeword"`
	LocationID         uint64             `json:"location_id"`
	EquippedID         uint64             `json:"equipped_id,omitempty"`
	PositionY          uint64             `json:"position_y"`
	PositionX          uint64             `json:"position_x"`
	AltPositionID      uint64             `json:"alt_position_id"`
	Type               string             `json:"type"`
	TypeID             uint64             `json:"type_id"`
	TypeName           string             `json:"type_name"`
	NrOfItemsInSockets uint64             `json:"nr_of_items_in_sockets"`
	ID                 uint64             `json:"id"`
	Level              uint64             `json:"level"`
	Quality            uint64             `json:"quality"`
	MultiplePictures   uint64             `json:"multiple_pictures"`
	PictureID          uint64             `json:"picture_id, omitempty"`
	ClassSpecific      uint64             `json:"class_specific"`
	LowQualityID       uint64             `json:"low_quality_id"`
	Timestamp          uint64             `json:"timestamp"`
	EarAttributes      earAttributes      `json:"ear_attributes"`
	DefenseRating      int64              `json:"defense_rating,omitempty"`
	MaxDurability      uint64             `json:"max_durability,omitempty"`
	CurrentDurability  uint64             `json:"current_durability,omitempty"`
	TotalNrOfSockets   uint64             `json:"total_nr_of_sockets"`
	Quantity           uint64             `json:"quantity,omitempty"`
	MagicPrefix        uint64             `json:"magic_prefix,omitempty"`
	MagicSuffix        uint64             `json:"magic_suffix,omitempty"`
	RunewordID         uint64             `json:"runeword_id,omitempty"`
	RunewordName       string             `json:"runeword_name,omitempty"`
	RunewordAttributes []magicAttribute   `json:"runeword_attributes"`
	SetID              uint64             `json:"set_id,omitempty"`
	SetName            string             `json:"set_name,omitempty"`
	SetListCount       uint64             `json:"set_list_count"`
	SetAttributes      [][]magicAttribute `json:"set_attributes"`
	RareName           string             `json:"rare_name,omitempty"`
	RareName2          string             `json:"rare_name2,omitempty"`
	MagicalNameIDs     []uint64           `json:"magical_name_ids,omitempty"`
	UniqueID           uint64             `json:"unique_id,omitempty"`
	UniqueName         string             `json:"unique_name,omitempty"`
	MagicAttributes    []magicAttribute   `json:"magic_attributes"`
	SocketedItems      []item             `json:"socketed_items"`
}

func (i *item) getTypeID() uint64 {

	if _, ok := armorCodes[i.Type]; ok {
		return armor
	}

	if _, ok := shieldCodes[i.Type]; ok {
		return shield
	}

	if _, ok := weaponCodes[i.Type]; ok {
		return weapon
	}

	return other
}

// Attributes that only exists on a player ear.
type earAttributes struct {
	Class uint64 `json:"class"`
	Level uint64 `json:"level"`
	Name  string `json:"name"`
}

// Note the values array is of the type int64, this is because some properties
// contain negative values, such as - % requirements.
type magicAttribute struct {
	ID     uint64  `json:"id"`
	Name   string  `json:"name"`
	Values []int64 `json:"values"`
}

type magicalProperty struct {
	Bits []uint
	Bias uint64
	Name string
}

// Item types, used to decide what attribute to give an item socketed with
// gems or runes mostly.
const (
	armor  = 0x01
	shield = 0x02
	weapon = 0x03
	other  = 0x04
)

// Item location IDs.
const (
	stored   = 0x00
	equipped = 0x01
	belt     = 0x02
	cursor   = 0x04
	socketed = 0x06
)

// Rarity IDs.
const (
	lowQuality        = 0x01
	normal            = 0x02
	highQuality       = 0x03
	magicallyEnhanced = 0x04
	partOfSet         = 0x05
	rare              = 0x06
	unique            = 0x07
	crafted           = 0x08
)

// Shield codes
var shieldCodes = map[string]string{
	"uow": "Aegis",
	"pa4": "Aerin Shield",
	"pa7": "Akaran Rondache",
	"pa6": "Akaran Targe",
	"pad": "Ancient Shield",
	"xts": "Ancient Shield",
	"xpk": "Barbed Shield",
	"upk": "Blade Barrier",
	"nef": "Bloodlord Skull",
	"bsh": "Bone Shield",
	"buc": "Buckler",
	"ne9": "Cantor Trophy",
	"pa5": "Crown Shield",
	"xuc": "Defender",
	"ne5": "Demon Head",
	"xit": "Dragon Shield",
	"ne7": "Fetish Trophy",
	"ne4": "Gargoyle Head",
	"gts": "Gothic Shield",
	"xsh": "Grim Shield",
	"pa9": "Gilded Shield",
	"nea": "Heirophant Trophy",
	"uuc": "Heater",
	"neg": "Hellspawn Skull",
	"pa3": "Heraldic Shield",
	"kit": "Kite Shield",
	"lrg": "Large Shield",
	"uml": "Luna",
	"neb": "Minion Skull",
	"uit": "Monarch",
	"ne6": "Mummified Trophy",
	"ned": "Overseer Skull",
	"xow": "Pavise",
	"ne1": "Preserved Head",
	"pa8": "Protector Shield",
	"pa2": "Rondache",
	"xml": "Round Shield",
	"paa": "Royal Shield",
	"pac": "Sacred Rondache",
	"pab": "Sacred Targe",
	"xrg": "Scutum",
	"ne8": "Sexton Trophy",
	"sml": "Small Shield",
	"spk": "Spiked Shield",
	"nee": "Succubus Skull",
	"pa1": "Targe",
	"tow": "Tower Shield",
	"ush": "Troll Nest",
	"ne3": "Unraveller Head",
	"paf": "Vortex Shield",
	"uts": "Ward",
	"pae": "Zakarum Shield",
	"ne2": "Zombie Head",
}

// Armor codes.
var armorCodes = map[string]string{
	"dr6": "Alpha Helm",
	"aar": "Ancient Armor",
	"dr3": "Antlers",
	"utp": "Archon Plate",
	"ulm": "Armet",
	"ba4": "Assault Helmet",
	"ba5": "Avenger Guard",
	"upl": "Balrog Skin",
	"xhl": "Basinet",
	"ztb": "Battle Belt",
	"xtb": "Battle Boots",
	"xtg": "Battle Gauntlets",
	"mbl": "Belt",
	"drb": "Blood Spirit",
	"bhm": "Bone Helm",
	"uh9": "Bone Visage",
	"uhn": "Boneweave",
	"umb": "Boneweave Boots",
	"mgl": "Bracers",
	"ulg": "Bramble Mitts",
	"brs": "Breast Plate",
	"cap": "Cap",
	"bab": "Carnage Helm",
	"xlm": "Casque",
	"mbt": "Chain Boots",
	"chn": "Chain Mail",
	"xul": "Chaos Armor",
	"ci0": "Circlet",
	"uhc": "Colossus Girdle",
	"bae": "Conquerer Crown",
	"urn": "Corona",
	"ci1": "Coronet",
	"crn": "Crown",
	"utg": "Crusader Gauntlets",
	"xrs": "Cuirass",
	"xsk": "Death Mask",
	"usk": "Demonhead",
	"xla": "Demonhide Armor",
	"xlb": "Demonhide Boots",
	"xlg": "Demonhide Gloves",
	"zlb": "Demonhide Sash",
	"bad": "Destroyer Helm",
	"ci3": "Diadem",
	"ung": "Diamond Mail",
	"drf": "Dream Spirit",
	"uui": "Dusk Shroud",
	"drd": "Earth Spirit",
	"xth": "Embossed Plate",
	"dr4": "Falcon Mask",
	"ba2": "Fanged Helm",
	"fld": "Field Plate",
	"fhl": "Full Helm",
	"ful": "Full Plate Mail",
	"bac": "Fury Visor",
	"hgl": "Gauntlets",
	"xui": "Ghost Armor",
	"uhl": "Giant Conch",
	"hbl": "Girdle",
	"lgl": "Gloves",
	"gth": "Gothic Plate",
	"xrn": "Grand Crown",
	"urs": "Great Hauberk",
	"ghm": "Great Helm",
	"dr7": "Griffon Headress",
	"xh9": "Grim Helm",
	"baf": "Guardian Crown",
	"hla": "Hard Leather Armor",
	"dr2": "Hawk Helm",
	"tbl": "Heavy Belt",
	"vbt": "Heavy Boots",
	"xmg": "Heavy Bracers",
	"vgl": "Heavy Gloves",
	"ult": "Hellforged Plate",
	"hlm": "Helm",
	"ba3": "Horned Helm",
	"dr8": "Hunter's Guise",
	"ukp": "Hydraskull",
	"urg": "Hyperion",
	"ba1": "Jawbone Cap",
	"ba6": "Jawbone Visor",
	"uld": "Kraken Shell",
	"uth": "Lacquered Plate",
	"lea": "Leather Armor",
	"lbt": "Leather Boots",
	"vbl": "Light Belt",
	"tgl": "Light Gauntlets",
	"ltp": "Light Plate",
	"tbt": "Light Plated Boots",
	"xng": "Linked Mail",
	"ba7": "Lion Helm",
	"ucl": "Loricated Mail",
	"xtp": "Mage Plate",
	"msk": "Mask",
	"xhn": "Mesh Armor",
	"zmb": "Mesh Belt",
	"xmb": "Mesh Boots",
	"utb": "Mirrored Boots",
	"umc": "Mithril Coil",
	"uhb": "Myrmidon Greaves",
	"uhg": "Ogre Gauntlets",
	"xar": "Ornate Plate",
	"hbt": "Plate Boots",
	"qui": "Quilted Armor",
	"ba8": "Rage Mask",
	"rng": "Ring Mail",
	"xpl": "Russet Armor",
	"uar": "Sacred Armor",
	"dr9": "Sacred Feathers",
	"xkp": "Sallet",
	"lbl": "Sash",
	"ba9": "Savage Helmet",
	"scl": "Scale Mail",
	"ula": "Scarab Husk",
	"uvb": "Scarabshell Boots",
	"xea": "Serpentskin Armor",
	"uul": "Shadow Plate",
	"uap": "Shako",
	"zvb": "Sharkskin Belt",
	"xvb": "Sharkskin Boots",
	"xvg": "Sharkskin Gloves",
	"xld": "Sharktooth Armor",
	"skp": "Skull Cap",
	"dre": "Sky Spirit",
	"baa": "Slayer Guard",
	"ulc": "Spiderweb Sash",
	"uhm": "Spired Helm",
	"dr5": "Spirit Mask",
	"spl": "Splint Mail",
	"stu": "Studded Leather",
	"drc": "Sun Spirit",
	"xlt": "Templar Coat",
	"ci2": "Tiara",
	"xcl": "Tigulated Mail",
	"dra": "Totemic Mask",
	"xtu": "Trellised Armor",
	"utc": "Troll Belt",
	"umg": "Vambraces",
	"uvg": "Vampirebone Gloves",
	"uvc": "Vampirefang Belt",
	"zhb": "War Belt",
	"xhb": "War Boots",
	"xhg": "War Gauntlets",
	"xap": "War Hat",
	"xhm": "Winged Helm",
	"utu": "Wire Fleece",
	"dr1": "Wolf Head",
	"uea": "Wyrmhide",
	"ulb": "Wyrmhide Boots",
}

// Weapon Codes.
var weaponCodes = map[string]string{
	"9gi": "Ancient Axe",
	"9wd": "Ancient Sword",
	"8lx": "Arbalest",
	"6ws": "Archon Staff",
	"am6": "Ashwood Bow",
	"7sm": "Ataghan",
	"axe": "Axe",
	"bal": "Balanced Axe",
	"bkf": "Balanced Knife",
	"8hx": "Balista",
	"7gs": "Balrog Blade",
	"7s7": "Balrog Spear",
	"9sp": "Barbed Club",
	"bar": "Bardiche",
	"bsw": "Bastard Sword",
	"btx": "Battle Axe",
	"7cs": "Battle Cestus",
	"9tk": "Battle Dart",
	"9wh": "Battle Hammer",
	"9s8": "Battle Scythe",
	"bst": "Battle Staff",
	"9bs": "Battle Sword",
	"9ba": "Bearded Axe",
	"9h9": "Bec De Corbin",
	"7wa": "Berserker Axe",
	"9vo": "Bill",
	"bld": "Blade",
	"6hb": "Blade Bow",
	"btl": "Blade Talons",
	"7dg": "Bone Knife",
	"bwn": "Bone Wand",
	"brn": "Brandistock",
	"bax": "Broad Axe",
	"bsd": "Broad Sword",
	"9wn": "Burnt Wand",
	"7ws": "Caduceus",
	"8lb": "Cedar Bow",
	"8cs": "Cedar Staff",
	"am7": "Ceremonial Bow",
	"ama": "Ceremonial Javelin",
	"am9": "Ceremonial Pike",
	"am8": "Ceremonial Spear",
	"ces": "Cestus",
	"7ga": "Champion Axe",
	"7b7": "Champion Sword",
	"gpm": "Choking Gas Potion",
	"8rx": "Chu-Ko-Nu",
	"9kr": "Cinquedeas",
	"ob4": "Clasped Orb",
	"clw": "Claws",
	"clm": "Claymore",
	"9ax": "Cleaver",
	"ob8": "Cloudy Sphere",
	"clb": "Club",
	"7fb": "Colossal Sword",
	"7gd": "Colossal Blade",
	"6hx": "Colossus Crossbow",
	"7vo": "Colossus Voulge",
	"cbw": "Composite Bow",
	"7bs": "Conquest Sword",
	"mxb": "Crossbow",
	"9mp": "Crowbill",
	"6l7": "Crusader Bow",
	"7pa": "Cryptic Axe",
	"7ls": "Cryptic Sword",
	"crs": "Crystal Sword",
	"ob7": "Crystalline Globe",
	"9cl": "Cudgel",
	"9sm": "Cutlass",
	"9cm": "Dacian Falx",
	"dgr": "Dagger",
	"7bt": "Decapitator",
	"d33": "Decoy Dagger",
	"6rx": "Demon Crossbow",
	"obd": "Demon Heart",
	"7mt": "Devil Star",
	"6s7": "Diamond Bow",
	"9cr": "Dimensional Blade",
	"obf": "Dimensional Shard",
	"dir": "Dirk",
	"9ws": "Divine Scepter",
	"2ax": "Double Axe",
	"8cb": "Double Bow",
	"ob5": "Dragon Stone",
	"ob1": "Eable Orb",
	"8sb": "Edge Bow",
	"6cs": "Elder Staff",
	"obc": "Eldritch Orb",
	"7sb": "Elegant Blade",
	"92h": "Espadon",
	"72a": "Ettin Axe",
	"9gd": "Executioner Sword",
	"opm": "Exploding Potion",
	"7ss": "Falcata",
	"flc": "Falchion",
	"7kr": "Fanged Knife",
	"9xf": "Fascia",
	"7la": "Feral Axe",
	"7lw": "Feral Claws",
	"fla": "Flail",
	"flb": "Flamberge",
	"9ma": "Flanged Mace",
	"7ta": "Flying Axe",
	"7tk": "Flying Knife",
	"9ta": "Francisca",
	"opl": "Fulmating Potion",
	"9tr": "Fuscina",
	"7gl": "Ghost Glaive",
	"7st": "Ghost Spear",
	"7yw": "Ghost Wand",
	"gix": "Giant Axe",
	"gis": "Giant Sword",
	"7wc": "Giant Thresher",
	"g33": "Gidbinn",
	"9ss": "Gladius",
	"glv": "Glaive",
	"7gi": "Glorious Axe",
	"ob6": "Glowing Orb",
	"cst": "Gnarled Staff",
	"6mx": "Gorgon Crossbow",
	"9ga": "Gothic Axe",
	"8lw": "Gothic Bow",
	"8bs": "Gothic Staff",
	"9b9": "Gothic Sword",
	"amc": "Grand Matron Bow",
	"gsc": "Grand Scepter",
	"9gw": "Grave Wand",
	"gax": "Great Axe",
	"6cb": "Great Bow",
	"gma": "Great Maul",
	"9pi": "Great Pilum",
	"7h7": "Great Poleaxe",
	"gsd": "Great Sword",
	"9lw": "Greater Claws",
	"9tw": "Greater Talons",
	"9wc": "Grim Scythe",
	"gwn": "Grim Wand",
	"hal": "Halberd",
	"hax": "Hand Axe",
	"9cs": "Hand Scythe",
	"9ts": "Harpoon",
	"9ha": "Hatchet",
	"axf": "HatchetHands",
	"obb": "Heavenly Stone",
	"hxb": "Heavy Crossbow",
	"hfh": "Hellforge Hammer",
	"7cm": "Highland Blade",
	"9qs": "Holy Water Sprinkler",
	"hdm": "Horadric Malus",
	"hst": "Horadric Staff",
	"hbw": "Hunters Bow",
	"9b8": "Hurlbat",
	"6lw": "Hydra Bow",
	"7fc": "Hydra Edge",
	"7ja": "Hyperion Javelin",
	"7sr": "Hyperion Spear",
	"9mt": "Jagged Star",
	"jav": "Javelin",
	"8ss": "Jo Staff",
	"ktr": "Katar",
	"qf1": "Khalim Flail",
	"9fl": "Knout",
	"kri": "Kriss",
	"9p9": "Lance",
	"lax": "Large Axe",
	"7bl": "Legend Spike",
	"72h": "Legend Sword",
	"7wh": "Legendary Mallet",
	"7bw": "Lich Wand",
	"lxb": "Light Crossbow",
	"9b7": "Lochaber Axe",
	"lbb": "Long Battle Bow",
	"lbw": "Long Bow",
	"8l8": "Long Siege Bow",
	"lst": "Long Staff",
	"lsd": "Long Sword",
	"lwb": "Long War Bow",
	"mac": "Mace",
	"am5": "Maiden Javelin",
	"am4": "Maiden Pike",
	"am3": "Maiden Spear",
	"7br": "Mancatcher",
	"9gm": "Martel de Fer",
	"amb": "Matriarchal Bow",
	"ame": "Matriarchal Pike",
	"amd": "Matriarchal Spear",
	"amf": "Matriarchal Javelin",
	"mau": "Maul",
	"7sc": "Mighty Scepter",
	"9la": "Military Axe",
	"mpi": "Military Pick",
	"7di": "Mithral Point",
	"mst": "Morning Star",
	"7wd": "Mythical Sword",
	"9wa": "Naga",
	"7o7": "Ogre Axe",
	"7m7": "Ogre Maul",
	"ops": "Oil Potion",
	"9pa": "Partizan",
	"6lx": "Pellet Bow",
	"9yw": "Petrified Wand",
	"7cr": "Phase Blade",
	"pik": "Pike",
	"pil": "Pilum",
	"9dg": "Poignard",
	"pax": "Poleaxe",
	"7wn": "Polished Wand",
	"8ls": "Quarter Staff",
	"9ar": "Quhab",
	"gps": "Rancid Gas Potion",
	"8hb": "Razor Bow",
	"am2": "Reflex Bow",
	"7ma": "Reinforced Mace",
	"rxb": "Repeating Crossbow",
	"9di": "Rondel",
	"8sw": "Rune Bow",
	"9sc": "Rune Scepter",
	"8ws": "Rune Staff",
	"9ls": "Rune Sword",
	"7tw": "Runic Talons",
	"sbr": "Sabre",
	"ob2": "Sacred Globe",
	"scp": "Scepter",
	"scm": "Scimitar",
	"skr": "Scissors Katar",
	"9qr": "Scissors Quhab",
	"7qr": "Scissors Suwayyah",
	"7fl": "Scourge",
	"scy": "Scythe",
	"7qs": "Seraph Rod",
	"6lb": "Shadow Bow",
	"9sb": "Shamshir",
	"6bs": "Shillelah",
	"sbb": "Short Battle Bow",
	"sbw": "Short Bow",
	"8s8": "Short Siege Bow",
	"ssp": "Short Spear",
	"sst": "Short Staff",
	"ssd": "Short Sword",
	"swb": "Short War Bow",
	"8mx": "Siege Crossbow",
	"7ba": "Silver Edged Axe",
	"9s9": "Simbilan",
	"7ax": "Small Crescent",
	"ob3": "Smoked Sphere",
	"ob9": "Sparkling Ball",
	"spr": "Spear",
	"spt": "Spetum",
	"9gl": "Spiculum",
	"6sb": "Spider Bow",
	"spc": "Spiked Club",
	"msf": "Staff Of The Kings",
	"am1": "Stag Bow",
	"6ls": "Stalagmite",
	"9bl": "Stilleto",
	"gpl": "Strangling Gas Potion",
	"7tr": "Stygian Pike",
	"7pi": "Stygian Pilum",
	"qf2": "Super Khalim Flail",
	"7ar": "Suwayyah",
	"oba": "Swirling Crystal",
	"9bt": "Tabar",
	"7s8": "Thresher",
	"tax": "Throwing Axe",
	"tkf": "Throwing Knife",
	"tsp": "Throwing Spear",
	"7gm": "Thunder Maul",
	"7ha": "Tomahawk",
	"9bw": "Tomb Wand",
	"tri": "Trident",
	"7cl": "Truncheon",
	"9fc": "Tulwar",
	"9gs": "Tusk Sword",
	"92a": "Twin Axe",
	"2hs": "Two Handed Axe",
	"7sp": "Tyrant Club",
	"7gw": "Unearthed Wand",
	"obe": "Vortex Orb",
	"vou": "Voulge",
	"6ss": "Walking Stick",
	"wnd": "Wand",
	"wax": "War Axe",
	"9m9": "War Club",
	"9bk": "War Dart",
	"7xf": "War Fist",
	"9br": "War Fork",
	"whm": "War Hammer",
	"9ja": "War Javelin",
	"7p7": "War Pike",
	"wsp": "War Scepter",
	"wsc": "War Scythe",
	"9sr": "War Spear",
	"7mp": "War Spike",
	"wst": "War Staff",
	"wsd": "War Sword",
	"6sw": "Ward Bow",
	"7b8": "Winged Axe",
	"7ts": "Winged Harpoon",
	"7bk": "Winged Knife",
	"leg": "Wirts Leg",
	"wrb": "Wrist Blade",
	"9wb": "Wrist Spike",
	"7wb": "Wrist Sword",
	"9st": "Yari",
	"ywn": "Yew Wand",
	"9fb": "Zweihander",
}

// Misc codes, like jewelry, gems, potions and runes.
var miscCodes = map[string]string{
	"gsv": "Amethyst",
	"r11": "Amn Rune",
	"amu": "Amulet",
	"yps": "Antidote Potion",
	"aqv": "Arrows",
	"bey": "Baal's Eye",
	"bks": "Bark Scroll",
	"r30": "Ber Rune",
	"cqv": "Bolts",
	"ass": "Book of Skill",
	"bet": "Burning Essence of Terror",
	"r32": "Cham Rune",
	"ceh": "Charged Essence of Hatred",
	"cm3": "Grand Charm",
	"cm2": "Large Charm",
	"cm1": "Small Charm",
	"gcv": "Chipped Amethyst",
	"gcw": "Chipped Diamond",
	"gcg": "Chipped Emerald",
	"gcr": "Chipped Ruby",
	"gcb": "Chipped Sapphire",
	"skc": "Chipped Skull",
	"gcy": "Chipped Topaz",
	"bkd": "Deciphered Bark Scroll",
	"dhn": "Diablo's Horn",
	"gsw": "Diamond",
	"r14": "Dol Rune",
	"r01": "El Rune",
	"r02": "Eld Rune",
	"elx": "Elixir",
	"gsg": "Emerald",
	"r05": "Eth Rune",
	"r19": "Fal Rune",
	"fed": "Festering Essence of Destruction",
	"gfv": "Flawed Amethyst",
	"gfw": "Flawed Diamond",
	"gfg": "Flawed Emerald",
	"gfr": "Flawed Ruby",
	"gfb": "Flawed Sapphire",
	"skf": "Flawed Skull",
	"gfy": "Flawed Topaz",
	"gzv": "Flawless Amethyst",
	"glw": "Flawless Diamond",
	"glg": "Flawless Emerald",
	"glr": "Flawless Ruby",
	"glb": "Flawless Sapphire",
	"skl": "Flawless Skull",
	"gly": "Flawless Topaz",
	"hpf": "Full Healing Potion",
	"mpf": "Full Mana Potion",
	"rvl": "Full Rejuvenation Potion",
	"gld": "Gold",
	"g34": "Gold Bird",
	"hp5": "Greater Healing Potion",
	"mp5": "Greater Mana Potion",
	"r25": "Gul Rune",
	"hp3": "Healing Potion",
	"hpo": "Healing Potion",
	"r15": "Hel Rune",
	"hrb": "Herb",
	"box": "Horadric Cube",
	"ibk": "Identify Book",
	"isc": "Identify Scroll",
	"r16": "Io Rune",
	"r24": "Ist Rune",
	"r06": "Ith Rune",
	"j34": "Jade Figurine",
	"r31": "Jah Rune",
	"jew": "Jewel",
	"pk3": "Key of Destruction",
	"pk2": "Key of Hate",
	"pk1": "Key of Terror",
	"qbr": "Khalim's Brain",
	"qey": "Khalim's Eye",
	"qhr": "Khalim's Heart",
	"r18": "Ko Rune",
	"bbb": "Lam Esens Tome",
	"bpl": "Large Blue Potion",
	"rpl": "Large Red Potion",
	"r20": "Lem Rune",
	"hp1": "Lesser Healing Potion",
	"mp1": "Lesser Mana Potion",
	"hp2": "Light Healing Potion",
	"mp2": "Light Mana Potion",
	"r28": "Lo Rune",
	"r17": "Lum Rune",
	"ice": "Maguffin",
	"r23": "Mal Rune",
	"mp3": "Mana Potion",
	"mpo": "Mana Potion",
	"mbr": "Mephisto's Brain",
	"luv": "Mephisto Key",
	"mss": "Mephisto Soul Stone",
	"r04": "Nef Rune",
	"r27": "Ohm Rune",
	"r09": "Ort Rune",
	"gpv": "Perfect Amethyst",
	"gpw": "Perfect Diamond",
	"gpg": "Perfect Emerald",
	"gpr": "Perfect Ruby",
	"gpb": "Perfect Sapphire",
	"skz": "Perfect Skull",
	"gpy": "Perfect Topaz",
	"ear": "Player Ear",
	"r21": "Pul Rune",
	"r08": "Ral Rune",
	"rvs": "Rejuvenation Potion",
	"rin": "Ring",
	"gsr": "Ruby",
	"gsb": "Sapphire",
	"0sc": "Scroll",
	"tr1": "Scroll of Horadric",
	"tr2": "Scroll of Malah",
	"xyz": "Potion of Life",
	"r13": "Shael Rune",
	"key": "Skeleton Key",
	"sku": "Skull",
	"bps": "Small Blue Potion",
	"rps": "Small Red Potion",
	"r12": "Sol Rune",
	"vps": "Stamina Potion",
	"std": "Standard of Heroes",
	"hp4": "Strong Healing Potion",
	"mp4": "Strong Mana Potion",
	"r29": "Sur Rune",
	"r07": "Tal Rune",
	"wms": "Thawing Potion",
	"r10": "Thul Rune",
	"r03": "Tir Rune",
	"toa": "Token of Absolution",
	"gsy": "Topaz",
	"tch": "Torch",
	"tbk": "Town Portal Book",
	"tsc": "Town Portal Scroll",
	"tes": "Twisted Essence of Suffering",
	"r22": "Um Rune",
	"r26": "Vex Rune",
	"vip": "Viper Amulet",
	"r33": "Zod Rune",
}

var rareNames = map[uint64]string{
	1:   "Bite",
	2:   "Scratch",
	3:   "Scalpel",
	4:   "Fang",
	5:   "Gutter",
	6:   "Thirst",
	7:   "Razor",
	8:   "Scythe",
	9:   "Edge",
	10:  "Saw",
	11:  "Splitter",
	12:  "Cleaver",
	13:  "Sever",
	14:  "Sunder",
	15:  "Rend",
	16:  "Mangler",
	17:  "Slayer",
	18:  "Reaver",
	19:  "Spawn",
	20:  "Gnash",
	21:  "Star",
	22:  "Blow",
	23:  "Smasher",
	24:  "Bane",
	25:  "Crusher",
	26:  "Breaker",
	27:  "Grinder",
	28:  "Crack",
	29:  "Mallet",
	30:  "Knell",
	31:  "Lance",
	32:  "Spike",
	33:  "Impaler",
	34:  "Skewer",
	35:  "Prod",
	36:  "Scourge",
	37:  "Wand",
	38:  "Wrack",
	39:  "Barb",
	40:  "Needle",
	41:  "Dart",
	42:  "Bolt",
	43:  "Quarrel",
	44:  "Fletch",
	45:  "Flight",
	46:  "Nock",
	47:  "Horn",
	48:  "Stinger",
	49:  "Quill",
	50:  "Goad",
	51:  "Branch",
	52:  "Spire",
	53:  "Song",
	54:  "Call",
	55:  "Cry",
	56:  "Spell",
	57:  "Chant",
	58:  "Weaver",
	59:  "Gnarl",
	60:  "Visage",
	61:  "Crest",
	62:  "Circlet",
	63:  "Veil",
	64:  "Hood",
	65:  "Mask",
	66:  "Brow",
	67:  "Casque",
	68:  "Visor",
	69:  "Cowl",
	70:  "Hide",
	71:  "Pelt",
	72:  "Carapace",
	73:  "Coat",
	74:  "Wrap",
	75:  "Suit",
	76:  "Cloak",
	77:  "Shroud",
	78:  "Jack",
	79:  "Mantle",
	80:  "Guard",
	81:  "Badge",
	82:  "Rock",
	83:  "Aegis",
	84:  "Ward",
	85:  "Tower",
	86:  "Shield",
	87:  "Wing",
	88:  "Mark",
	89:  "Emblem",
	90:  "Hand",
	91:  "Fist",
	92:  "Claw",
	93:  "Clutches",
	94:  "Grip",
	95:  "Grasp",
	96:  "Hold",
	97:  "Torch",
	98:  "Finger",
	99:  "Knuckle",
	100: "Shank",
	101: "Spur",
	102: "Tread",
	103: "Stalker",
	104: "Greave",
	105: "Blazer",
	106: "Nails",
	107: "Trample",
	108: "Brogues",
	109: "Track",
	110: "Slippers",
	111: "Clasp",
	112: "Buckle",
	113: "Harness",
	114: "Lock",
	115: "Fringe",
	116: "Winding",
	117: "Chain",
	118: "Strap",
	119: "Lash",
	120: "Cord",
	121: "Knot",
	122: "Circle",
	123: "Loop",
	124: "Eye",
	125: "Turn",
	126: "Spiral",
	127: "Coil",
	128: "Gyre",
	129: "Band",
	130: "Whorl",
	131: "Talisman",
	132: "Heart",
	133: "Noose",
	134: "Necklace",
	135: "Collar",
	136: "Beads",
	137: "Torc",
	138: "Gorget",
	139: "Scarab",
	140: "Wood",
	141: "Brand",
	142: "Bludgeon",
	143: "Cudgel",
	144: "Loom",
	145: "Harp",
	146: "Master",
	147: "Barl",
	148: "Hew",
	149: "Crook",
	150: "Mar",
	151: "Shell",
	152: "Stake",
	153: "Picket",
	154: "Pale",
	155: "Flange",
	156: "Beast",
	157: "Eagle",
	158: "Raven",
	159: "Viper",
	160: "Ghoul",
	161: "Skull",
	162: "Blood",
	163: "Dread",
	164: "Doom",
	165: "Grim",
	166: "Bone",
	167: "Death",
	168: "Shadow",
	169: "Storm",
	170: "Rune",
	171: "Plague",
	172: "Stone",
	173: "Wraith",
	174: "Spirit",
	175: "Storm",
	176: "Demon",
	177: "Cruel",
	178: "Empyrion",
	179: "Bramble",
	180: "Pain",
	181: "Loath",
	182: "Glyph",
	183: "Imp",
	184: "Fiendra",
	185: "Hailstone",
	186: "Gale",
	187: "Dire",
	188: "Soul",
	189: "Brimstone",
	190: "Corpse",
	191: "Carrion",
	192: "Armageddon",
	193: "Havoc",
	194: "Bitter",
	195: "Entropy",
	196: "Chaos",
	197: "Order",
	198: "Rule",
	199: "Warp",
	200: "Rift",
	201: "Corruption",
}

var setNames = map[uint64]string{
	0:   "Civerb's Ward",
	1:   "Civerb's Icon",
	2:   "Civerb's Cudgel",
	3:   "Hsaru's Iron Heel",
	4:   "Hsaru's Iron Fist",
	5:   "Hsaru's Iron Stay",
	6:   "Cleglaw's Tooth",
	7:   "Cleglaw's Claw",
	8:   "Cleglaw's Pincers",
	9:   "Iratha's Collar",
	10:  "Iratha's Cuff",
	11:  "Iratha's Coil",
	12:  "Iratha's Cord",
	13:  "Isenhart's Lightbrand",
	14:  "Isenhart's Parry",
	15:  "Isenhart's Case",
	16:  "Isenhart's Horns",
	17:  "Vidala's Barb",
	18:  "Vidala's Fetlock",
	19:  "Vidala's Ambush",
	20:  "Vidala's Snare",
	21:  "Milabrega's Orb",
	22:  "Milabrega's Rod",
	23:  "Milabrega's Diadem",
	24:  "Mialbrega's Robe",
	25:  "Cathan's Rule",
	26:  "Cathan's Mesh",
	27:  "Cathan's Visage",
	28:  "Cathan's Sigil",
	29:  "Cathan's Seal",
	30:  "Tancred's Crowbill",
	31:  "Tancred's Spine",
	32:  "Tancred's Hobnails",
	33:  "Tancred's Weird",
	34:  "Tancred's Skull",
	35:  "Sigon's Gage",
	36:  "Sigon's Visor",
	37:  "Sigon's Shelter",
	38:  "Sigon's Sabot",
	39:  "Sigon's Wrap",
	40:  "Sigon's Guard",
	41:  "Infernal Cranium",
	42:  "Infernal Torch",
	43:  "Infernal Sign",
	44:  "Berserker's Headgear",
	45:  "Berserker's Hauberk",
	46:  "Berserker's Hatchet",
	47:  "Death's Hand",
	48:  "Death's Guard",
	49:  "Death's Touch",
	50:  "Angelic Sickle",
	51:  "Angelic Mantle",
	52:  "Angelic Halo",
	53:  "Angelic Wings",
	54:  "Arctic Horn",
	55:  "Arctic Furs",
	56:  "Arctic Binding",
	57:  "Arctic Mitts",
	58:  "Arcanna's Sign",
	59:  "Arcanna's Deathwand",
	60:  "Arcanna's Head",
	61:  "Arcanna's Flesh",
	62:  "Natalya's Totem",
	63:  "Natalya's Mark",
	64:  "Natalya's Shadow",
	65:  "Natalya's Soul",
	66:  "Aldur's Stony Gaze",
	67:  "Aldur's Deception",
	68:  "Aldur's Rhythm",
	69:  "Aldur's Advance",
	70:  "Immortal King's Will",
	71:  "Immortal King's Soul Cage",
	72:  "Immortal King's Detail",
	73:  "Immortal King's Forge",
	74:  "Immortal King's Pillar",
	75:  "Immortal King's Stone Crusher",
	76:  "Tal Rasha's Fire-Spun Cloth",
	77:  "Tal Rasha's Adjudication",
	78:  "Tal Rasha's Lidless Eye",
	79:  "Tal Rasha's Guardianship",
	80:  "Tal Rasha's Horadric Crest",
	81:  "Griswold's Valor",
	82:  "Griswold's Heart",
	83:  "Griswold's Redemption",
	84:  "Griswold's Honor",
	85:  "Trang-Oul's Guise",
	86:  "Trang-Oul's Scales",
	87:  "Trang-Oul's Wing",
	88:  "Trang-Oul's Claws",
	89:  "Trang-Oul's Girth",
	90:  "M'avina's True Sight",
	91:  "M'avina's Embrace",
	92:  "M'avina's Icy Clutch",
	93:  "M'avina's Tenet",
	94:  "M'avina's Caster",
	95:  "Telling of Beads",
	96:  "Laying of Hands",
	97:  "Rite of Passage",
	98:  "Dark Adherent",
	99:  "Credendum",
	100: "Dangoon's Teaching",
	101: "Taebaek's Glory",
	102: "Haemosu's Adament",
	103: "Ondal's Almighty",
	104: "Guillaume's Face",
	105: "Wilhelm's Pride",
	106: "Magnus' Skin",
	107: "Wihtstan's Guard",
	108: "Hwanin's Splendor",
	109: "Hwanin's Refuge",
	110: "Hwanin's Blessing",
	111: "Hwanin's Justice",
	112: "Sazabi's Cobalt Redeemer",
	113: "Sazabi's Ghost Liberator",
	114: "Sazabi's Mental Sheath",
	115: "Bul-Katho's Sacred Charge",
	116: "Bul-Katho's Tribal Guardian",
	117: "Cow King's Horns",
	118: "Cow King's Hide",
	119: "Cow King's Hooves",
	120: "Naj's Puzzler",
	121: "Naj's Light Plate",
	122: "Naj's Circlet",
	123: "Sander's Paragon",
	124: "Sander's Riprap",
	125: "Sander's Taboo",
	126: "Sander's Superstition",
}

var runewordNames = map[uint64]string{
	27:   "Ancient's Pledge",
	30:   "Beast",
	32:   "Black",
	34:   "Bone",
	35:   "Bramble",
	36:   "Brand",
	37:   "Breath of the Dying",
	39:   "Call to Arms",
	40:   "Chains of Honor",
	42:   "Chaos",
	43:   "Crescent Moon",
	46:   "Death",
	51:   "Desctruction",
	52:   "Doom",
	53:   "Dragon",
	55:   "Dream",
	56:   "Duress",
	57:   "Edge",
	59:   "Enigma",
	60:   "Enlightenment",
	62:   "Eternity",
	63:   "Exile",
	64:   "Faith",
	65:   "Famine",
	67:   "Fortitude",
	70:   "Fury",
	71:   "Gloom",
	73:   "Widowmaker",
	74:   "Hand of Justice",
	75:   "Harmory",
	77:   "Heart of the Oak",
	80:   "Holy Thunder",
	81:   "Honor",
	85:   "Ice",
	86:   "Infinity",
	88:   "Insight",
	91:   "King's Grace",
	92:   "Kingslayer",
	95:   "Last Wish",
	97:   "Lawbringer",
	98:   "Leaf",
	100:  "Lionheart",
	101:  "Lore",
	106:  "Malice",
	107:  "Melody",
	108:  "Memory",
	112:  "Myth",
	113:  "Nadir",
	116:  "Oath",
	117:  "Obedience",
	120:  "Passion",
	123:  "Peace",
	124:  "Winter",
	128:  "Phoenix",
	134:  "Pride",
	135:  "Principle",
	137:  "Prudence",
	141:  "Radiance",
	142:  "Rain",
	145:  "Rhyme",
	146:  "Rift",
	147:  "Sanctuary",
	151:  "Silence",
	153:  "Smoke",
	155:  "Spirit",
	156:  "Splendor",
	158:  "Stealth",
	159:  "Steel",
	162:  "Stone",
	164:  "Strength",
	173:  "Treachery",
	179:  "Venom",
	185:  "Wealth",
	187:  "White",
	188:  "Wind",
	193:  "Wrath",
	195:  "Zephyr",
	2718: "Delirium",
}

var uniqueNames = map[uint64]string{
	0:   "The Gnasher",
	1:   "Deathspade",
	2:   "Bladebone",
	3:   "Skull splitter",
	4:   "Rakescar",
	5:   "Axe of Fechmar",
	6:   "Goreshovel",
	7:   "The Chiefthan",
	8:   "Brainhew",
	9:   "Humongous",
	10:  "Torch of Iros",
	11:  "Maelstorm",
	12:  "Gravenspine",
	13:  "Umes Lament",
	14:  "Felloak",
	15:  "Knell Striker",
	16:  "Rusthandle",
	17:  "Stormeye",
	18:  "Stoutnail",
	19:  "Crushflange",
	20:  "Bloodrise",
	21:  "The Generals Tan Do Li Ga",
	22:  "Ironstone",
	23:  "Bonesnap",
	24:  "Steeldriver",
	25:  "Rixot's Keen",
	26:  "Blood Crescent",
	27:  "Skewer of Krintiz",
	28:  "Gleamscythe",
	29:  "Azurewrath",
	30:  "Griswold's Edge",
	31:  "Hellplague",
	32:  "Culwens Point",
	33:  "Shadowfang",
	34:  "Soulflay",
	35:  "Kinemils Awl",
	36:  "Blacktongue",
	37:  "Ripsaw",
	38:  "The Patriarch",
	39:  "Gull",
	40:  "The Diggler",
	41:  "The Jade Tan Do",
	42:  "Spectral Shard",
	43:  "The Dragon Chang",
	44:  "Razortine",
	45:  "Bloodthief",
	46:  "Lance of Yaggai",
	47:  "The Tannr Gorerod",
	48:  "Dimoaks Hew",
	49:  "Steelgoad",
	50:  "Soul Harvest",
	51:  "The Battlebranch",
	52:  "Woestave",
	53:  "The Grim Reaper",
	54:  "Bane Ash",
	55:  "Serpent Lord",
	56:  "Spire of Lazarus",
	57:  "The Salamander",
	58:  "The Iron Jang Bong",
	59:  "Pluckeye",
	60:  "Witherstring",
	61:  "Raven Claw",
	62:  "Rogue's Bow",
	63:  "Stormstrike",
	64:  "Wizendraw",
	65:  "Hellclap",
	66:  "Blastbark",
	67:  "Leadcrow",
	68:  "Ichorsting",
	69:  "Hellcast",
	70:  "Doomslayer",
	71:  "Biggin's Bonnet",
	72:  "Tarnhelm",
	73:  "Coif of Glory",
	74:  "Duskdeep",
	75:  "Wormskull",
	76:  "Howltusk",
	77:  "Undead Crown",
	78:  "The Face of Horror",
	79:  "Greyform",
	80:  "Blinkbat's Form",
	81:  "The Centurion",
	82:  "Twitchthroe",
	83:  "Darkglow",
	84:  "Hawkmail",
	85:  "Sparking Mail",
	86:  "Venom Ward",
	87:  "Iceblink",
	88:  "Boneflesh",
	89:  "Rockfleece",
	90:  "Rattlecage",
	91:  "Goldskin",
	92:  "Victors Silk",
	93:  "Heavenly Garb",
	94:  "Pelta Lunata",
	95:  "Umbral Disk",
	96:  "Stormguild",
	97:  "Wall of the Eyeless",
	98:  "Swordback Hold",
	99:  "Steelclash",
	100: "Bverrit Keep",
	101: "The Ward",
	102: "The Hand of Broc",
	103: "Bloodfist",
	104: "Chance Guards",
	105: "Magefist",
	106: "Frostburn",
	107: "Hotspur",
	108: "Gorefoot",
	109: "Treads of Cthon",
	110: "Goblin Toe",
	111: "Tearhaunch",
	112: "Lenymo",
	113: "Snakecord",
	114: "Nightsmoke",
	115: "Goldwrap",
	116: "Bladebuckle",
	117: "Nokozan Relic",
	118: "The Eye of Etlich",
	119: "The Mahim-Oak Curio",
	120: "Nagelring",
	121: "Manald Heal",
	122: "The Stone of Jordan",
	123: "Amulet of the Viper",
	124: "Staff of Kings",
	125: "Horadric Staff",
	126: "Hell Forge Hammer",
	127: "Khalim's Flail",
	128: "Super Khalim's Flail",
	129: "Coldkill",
	130: "Butcher's Pupil",
	131: "Islestrike",
	132: "Pompe's Wrath",
	133: "Guardian Naga",
	134: "Warlord's Trust",
	135: "Spellsteel",
	136: "Stormrider",
	137: "Boneslayer Blade",
	138: "The Minataur",
	139: "Suicide Branch",
	140: "Carin Shard",
	141: "Arm of King Leoric",
	142: "Blackhand Key",
	143: "Dark Clan Crusher",
	144: "Zakarum's Hand",
	145: "The Fetid Sprinkler",
	146: "Hand of Blessed Light",
	147: "Fleshrender",
	148: "Sureshrill Frost",
	149: "Moonfall",
	150: "Baezil's Vortex",
	151: "Earthshaker",
	152: "Bloodtree Stump",
	153: "The Gavel of Pain",
	154: "Bloodletter",
	155: "Coldsteel Eye",
	156: "Hexfire",
	157: "Blade of Ali Baba",
	158: "Ginther's Rift",
	159: "Headstriker",
	160: "Plague Bearer",
	161: "The Atlantian",
	162: "Crainte Vomir",
	163: "Bing Sz Wang",
	164: "The Vile Husk",
	165: "Cloudcrack",
	166: "Todesfaelle Flamme",
	167: "Swordguard",
	168: "Spineripper",
	169: "Heart Carver",
	170: "Blackbog's Sharp",
	171: "Stormspike",
	172: "The Impaler",
	173: "Kelpie Snare",
	174: "Soulfeast Tine",
	175: "Hone Sundan",
	176: "Spire of Honor",
	177: "The Meat Scraper",
	178: "Blackleach Blade",
	179: "Athena's Wrath",
	180: "Pierre Tombale Couant",
	181: "Husoldal Evo",
	182: "Grim's Burning Dead",
	183: "Razorswitch",
	184: "Ribcracker",
	185: "Chromatic Ire",
	186: "Warpspear",
	187: "Skullcollector",
	188: "Skystrike",
	189: "Riphook",
	190: "Kuko Shakaku",
	191: "Endlesshail",
	192: "Whichwild String",
	193: "Cliffkiller",
	194: "Magewrath",
	195: "Godstrike Arch",
	196: "Langer Briser",
	197: "Pus Spiter",
	198: "Buriza-Do Kyanon",
	199: "Demon Machine",
	200: "Armor (Unknown)",
	201: "Peasent Crown",
	202: "Rockstopper",
	203: "Stealskull",
	204: "Darksight Helm",
	205: "Valkyrie Wing",
	206: "Crown of Thieves",
	207: "Blckhorn's Face",
	208: "Vampire Gaze",
	209: "The Spirit Shroud",
	210: "Skin of the Vipermagi",
	211: "Skin of the Flayed One",
	212: "Ironpelt",
	213: "Spiritforge",
	214: "Crow Caw",
	215: "Shaftstop",
	216: "Duriel's Shell",
	217: "Skullder's Ire",
	218: "Guardian Angel",
	219: "Toothrow",
	220: "Atma's Wail",
	221: "Black Hades",
	222: "Corpsemourn",
	223: "Que-Hegan's Wisdom",
	224: "Visceratuant",
	225: "Mosers Blessed Circle",
	226: "Stormchaser",
	227: "Tiamat's Rebuke",
	228: "Kerke's Sanctuary",
	229: "Radimant's Sphere",
	230: "Lidless Wall",
	231: "Lance Guard",
	232: "Venom Grip",
	233: "Gravepalm",
	234: "Ghoulhide",
	235: "Lavagout",
	236: "Hellmouth",
	237: "Infernostride",
	238: "Waterwalk",
	239: "Silkweave",
	240: "Wartraveler",
	241: "Gorerider",
	242: "String of Ears",
	243: "Razortail",
	244: "Gloomstrap",
	245: "Snowclash",
	246: "Thundergod's Vigor",
	247: "Elite unique",
	248: "Harlequin Crest",
	249: "Veil of Steel",
	250: "The Gladiator's Bane",
	251: "Arkaine's Valor",
	252: "Blackoak Shield",
	253: "Stormshield",
	254: "Hellslayer",
	255: "Messerschmidt's Reaver",
	256: "Baranar's Star",
	257: "Schaefer's Hammer",
	258: "The Cranium Basher",
	259: "Lightsabre",
	260: "Doombringer",
	261: "The Grandfather",
	262: "Wizardspike",
	263: "Constricting Ring",
	264: "Stormspire",
	265: "Eaglehorn",
	266: "Windforce",
	267: "Ring",
	268: "Bul Katho's Wedding Band",
	269: "The Cat's Eye",
	270: "The Rising Sun",
	271: "Crescent Moon",
	272: "Mara's Kaleidoscope",
	273: "Atma's Scarab",
	274: "Dwarf Star",
	275: "Raven Frost",
	276: "Highlord's Wrath",
	277: "Saracen's Chance",
	278: "Class specific",
	279: "Arreat's Face",
	280: "Homunculus",
	281: "Titan's Revenge",
	282: "Lycander's Aim",
	283: "Lycander's Flank",
	284: "The Oculus",
	285: "Herald of Zakarum",
	286: "Cutthroat",
	287: "Jalal's Mane",
	288: "The Scalper",
	289: "Bloodmoon",
	290: "Djinnslayer",
	291: "Deathbit",
	292: "Warshrike",
	293: "Gutsiphon",
	294: "Razoredge",
	295: "Gore Ripper",
	296: "Demonlimb",
	297: "Steelshade",
	298: "Tomb Reaver",
	299: "Death's Web",
	300: "Nature's Peace",
	301: "Azurewrath",
	302: "Seraph's Hymn",
	303: "Zakarum's Salvation",
	304: "Fleshripper",
	305: "Odium",
	306: "Horizon's Tornado",
	307: "Stone Crusher",
	308: "Jadetalon",
	309: "Shadowdancer",
	310: "Cerebus",
	311: "Tyrael's Might",
	312: "Souldrain",
	313: "Runemaster",
	314: "Deathcleaver",
	315: "Executioner's Justice",
	316: "Stoneraven",
	317: "Leviathan",
	318: "Larzuk's Champion",
	319: "Wisp",
	320: "Gargoyle's Bite",
	321: "Lacerator",
	322: "Mang Song's Lesson",
	323: "Viperfork",
	324: "Ethereal Edge",
	325: "Demonhorn's Edge",
	326: "The Reaper's Toll",
	327: "Spiritkeeper",
	328: "Hellrack",
	329: "Alma Negra",
	330: "Darkforge Spawn",
	331: "Widowmaker",
	332: "Bloodraven's Charge",
	333: "Ghostflame",
	334: "Shadowkiller",
	335: "Gimmershred",
	336: "Griffon's Eye",
	337: "Windhammer",
	338: "Thunderstroke",
	339: "Giant Maimer",
	340: "Demon's Arch",
	341: "Boneflame",
	342: "Steelpillar",
	343: "Nightwing's Veil",
	344: "Crown of Ages",
	345: "Andariel's Visage",
	346: "Darkfear",
	347: "Dragonscale",
	348: "Steel Carapice",
	349: "Medusa's Gaze",
	350: "Ravenlore",
	351: "Boneshade",
	352: "Nethercrow",
	353: "Flamebellow",
	354: "Fathom",
	355: "Wolfhowl",
	356: "Spirit Ward",
	357: "Kira's Guardian",
	358: "Ormus Robes",
	359: "Gheed's Fortune",
	360: "Stormlash",
	361: "Halaberd's Reign",
	362: "Warriv's Warder",
	363: "Spike Thorn",
	364: "Dracul's Grasp",
	365: "Frostwind",
	366: "Templar's Might",
	367: "Eschuta's Temper",
	368: "Firelizard's Talons",
	369: "Sandstorm Trek",
	370: "Marrowwalk",
	371: "Heaven's Light",
	372: "Merman's Speed",
	373: "Arachnid Mesh",
	374: "Nosferatu's Coil",
	375: "Metalgrid",
	376: "Verdugo's Hearty Cord",
	377: "Sigurd's Staunch",
	378: "Carrion Wind",
	379: "Giantskull",
	380: "Ironward",
	381: "Annihilus",
	382: "Arioc's Needle",
	383: "Cranebeak",
	384: "Nord's Tenderizer",
	385: "Earthshifter",
	386: "Wraithflight",
	387: "Bonehew",
	388: "Ondal's Wisdom",
	389: "The Reedeemer",
	390: "Headhunter's Glory",
	391: "Steelrend",
	392: "Rainbow Facet",
	393: "Rainbow Facet",
	394: "Rainbow Facet",
	395: "Rainbow Facet",
	396: "Rainbow Facet",
	397: "Rainbow Facet",
	398: "Rainbow Facet",
	399: "Rainbow Facet",
	400: "Hellfire Torch",
}

var magicalProperties = map[uint64]magicalProperty{
	0:  {Bits: []uint{8}, Bias: 32, Name: "+{0} to Strength"},
	1:  {Bits: []uint{7}, Bias: 32, Name: "+{0} to Energy"},
	2:  {Bits: []uint{7}, Bias: 32, Name: "+{0} to Dexterity"},
	3:  {Bits: []uint{7}, Bias: 32, Name: "+{0} to Vitality"},
	7:  {Bits: []uint{9}, Bias: 32, Name: "+{0} to Life"},
	9:  {Bits: []uint{8}, Bias: 32, Name: "+{0} to Mana"},
	11: {Bits: []uint{8}, Bias: 32, Name: "+{0} to Maximum Stamina"},
	16: {Bits: []uint{9}, Name: "+{0}% Enhanced Defense"},
	17: {Bits: []uint{9, 9}, Name: "+{0}% Enhanced Damage"},
	19: {Bits: []uint{10}, Name: "+{0} to Attack rating"},
	20: {Bits: []uint{6}, Name: "+{0}% Increased chance of blocking"},
	21: {Bits: []uint{6}, Name: "+{0} to Minimum 1-handed damage"},
	22: {Bits: []uint{7}, Name: "+{0} to Maximum 1-handed damage"},
	23: {Bits: []uint{6}, Name: "+{0} to Minimum 2-handed damage"},
	24: {Bits: []uint{7}, Name: "+{0} to Maximum 2-handed damage"},
	27: {Bits: []uint{8}, Name: "Regenerate Mana {0}%"},
	28: {Bits: []uint{8}, Name: "Heal Stamina {0}%"},
	31: {Bits: []uint{11}, Bias: 10, Name: "+{0} Defense"},
	32: {Bits: []uint{9}, Name: "+{0} vs. Missile"},
	33: {Bits: []uint{10}, Bias: 10, Name: "+{0} vs. Melee"},
	34: {Bits: []uint{6}, Name: "Damage Reduced by {0}"},
	35: {Bits: []uint{6}, Name: "Magic Damage Reduced by {0}"},
	36: {Bits: []uint{8}, Name: "Damage Reduced by {0}%"},
	37: {Bits: []uint{8}, Name: "Magic Resist +{0}%"},
	38: {Bits: []uint{8}, Name: "+{0}% to Maximum Magic Resist"},
	39: {Bits: []uint{8}, Bias: 50, Name: "Fire Resist +{0}%"},
	40: {Bits: []uint{5}, Name: "+{0}% to Maximum Fire Resist"},
	41: {Bits: []uint{8}, Bias: 50, Name: "Lightning Resist +{0}%"},
	42: {Bits: []uint{5}, Name: "+{0}% to Maximum Lightning Resist"},
	43: {Bits: []uint{8}, Bias: 50, Name: "Cold Resist +{0}%"},
	44: {Bits: []uint{5}, Name: "+{0}% to Maximum Cold Resist"},
	45: {Bits: []uint{8}, Bias: 50, Name: "Poison Resist +{0}%"},
	46: {Bits: []uint{5}, Name: "+{0}% to Maximum Poison Resist"},
	48: {Bits: []uint{8, 9}, Name: "Adds {0}-{1} Fire Damage"},
	50: {Bits: []uint{6, 10}, Name: "Adds {0}-{1} Lightning Damage"},
	52: {Bits: []uint{8, 9}, Name: "Adds {0}-{1} Magic Damage"},
	54: {Bits: []uint{8, 9, 8}, Name: "Adds {0}-{1} Cold Damage"},
	57: {Bits: []uint{10, 10, 9}, Name: "Adds {0}-{1} Poison Damage over {2} Seconds"},
	60: {Bits: []uint{7}, Name: "{0}% Life Stolen Per Hit"},
	62: {Bits: []uint{7}, Name: "{0}% Mana Stolen Per Hit"},
	73: {Bits: []uint{8}, Name: "+{0} Maximum Durability"},
	74: {Bits: []uint{6}, Bias: 30, Name: "Replenish Life +{0}"},
	75: {Bits: []uint{7}, Bias: 20, Name: "Increase Maximum Durability {0}%"},
	76: {Bits: []uint{6}, Bias: 10, Name: "Increase Maximum Life {0}%"},
	77: {Bits: []uint{6}, Bias: 10, Name: "Increase Maximum Mana {0}%"},
	78: {Bits: []uint{7}, Name: "Attacker Takes Damage of {0}"},
	79: {Bits: []uint{9}, Bias: 100, Name: "{0}% Extra Gold from Monsters"},
	80: {Bits: []uint{8}, Bias: 100, Name: "{0}% Better Chance of Getting Magic Items"},
	81: {Bits: []uint{7}, Name: "Knockback"},

	// First value is class, second is skill level, but they're printed in reverse
	// e.g. "+3 To Sorceress Skill Levels"
	83: {Bits: []uint{3, 3}, Name: "+{1} to {0} Skill Levels"},
	84: {Bits: []uint{3, 3}, Name: "+{1} to {0} Skill Levels"},

	// TODO: Check if experience gained really have a bias of 50.
	85: {Bits: []uint{9}, Bias: 50, Name: "{0}% To Experience Gained"},
	86: {Bits: []uint{7}, Name: "+{0} Life After Each Kill"},
	87: {Bits: []uint{7}, Name: "Reduces Prices {0}%"},
	89: {Bits: []uint{4}, Bias: 4, Name: "+{0} to Light Radius"},
	// This property is not displayed on the item, but its effect is to alter
	// the color of the ambient light.
	90: {Bits: []uint{5}, Name: "Ambient light"},
	// After subtracting the bias, this is usually a negative number.
	91: {Bits: []uint{8}, Bias: 100, Name: "Requirements {0}%"},
	92: {Bits: []uint{7}, Name: "Level requirements +{0} (Invisible)"},
	93: {Bits: []uint{7}, Bias: 20, Name: "{0}% Increased Attack Speed"},
	96: {Bits: []uint{7}, Bias: 20, Name: "{0}% Faster Run/Walk"},

	// Number of levels to a certain skill, e.g. +1 To Teleport.
	97:  {Bits: []uint{9, 6}, Name: "+{1} To {0}"},
	99:  {Bits: []uint{7}, Bias: 20, Name: "{0}% Faster Hit Recovery"},
	102: {Bits: []uint{7}, Bias: 20, Name: "{0}% Faster Block Rate"},
	105: {Bits: []uint{7}, Bias: 20, Name: "{0}% Faster Cast Rate"},

	// These properties usually applied to class specific items,
	// first value selects the skill, the second determines how many
	// additional skill points are given.
	107: {Bits: []uint{9, 3}, Name: "+{1} To {0}"},
	108: {Bits: []uint{1}, Name: "Rest In Peace"},
	109: {Bits: []uint{9, 5}, Name: "+{1} to spell {0} (char_class Only)"},
	181: {Bits: []uint{9, 5}, Name: "+{1} to spell {0} (char_class Only)"},
	182: {Bits: []uint{9, 5}, Name: "+{1} to spell {0} (char_class Only)"},
	183: {Bits: []uint{9, 5}, Name: "+{1} to spell {0} (char_class Only)"},
	184: {Bits: []uint{9, 5}, Name: "+{1} to spell {0} (char_class Only)"},
	185: {Bits: []uint{9, 5}, Name: "+{1} to spell {0} (char_class Only)"},
	186: {Bits: []uint{9, 5}, Name: "+{1} to spell {0} (char_class Only)"},
	187: {Bits: []uint{9, 5}, Name: "+{1} to spell {0} (char_class Only)"},

	110: {Bits: []uint{8}, Bias: 20, Name: "Poison Length Reduced by {0}%"},
	111: {Bits: []uint{9}, Bias: 20, Name: "Damage +{0}"},
	112: {Bits: []uint{7}, Name: "Hit Causes Monsters to Flee {0}%"},
	113: {Bits: []uint{7}, Name: "Hit Blinds Target +{0}"},
	114: {Bits: []uint{6}, Name: "{0}% Damage Taken Goes to Mana"},
	// The value of the data field is always 1.
	115: {Bits: []uint{1}, Name: "Ignore Target Defense"},
	116: {Bits: []uint{7}, Name: "{0}% Target Defense"},
	// The value of the data field is always 1.
	117: {Bits: []uint{7}, Name: "Prevent Monster Heal"},
	// The value of the data field is always 1.
	118: {Bits: []uint{1}, Name: "Half Freeze Duration"},
	119: {Bits: []uint{9}, Bias: 20, Name: "{0}% Bonus to Attack Rating"},
	120: {Bits: []uint{7}, Bias: 128, Name: "{0} to Monster Defense Per Hit"},
	121: {Bits: []uint{9}, Bias: 20, Name: "+{0}% Damage to Demons"},
	122: {Bits: []uint{9}, Bias: 20, Name: "+{0}% Damage to Undead"},
	123: {Bits: []uint{10}, Bias: 128, Name: "+{0} to Attack Rating against Demons"},
	124: {Bits: []uint{10}, Bias: 128, Name: "+{0} to Attack Rating against Undead"},
	126: {Bits: []uint{4}, Name: "+{0} to Fire Skills"},
	127: {Bits: []uint{3}, Name: "+{0} to All Skill Levels"},
	128: {Bits: []uint{5}, Name: "Attacker Takes Lightning Damage of {0}"},
	134: {Bits: []uint{5}, Name: "Freezes Target +{0}"},
	135: {Bits: []uint{7}, Name: "{0}% Chance of Open Wounds"},
	136: {Bits: []uint{7}, Name: "{0}% Chance of Crushing Blow"},
	137: {Bits: []uint{7}, Name: "+{0} Kick Damage"},
	138: {Bits: []uint{7}, Name: "+{0} to Mana After Each Kill"},
	139: {Bits: []uint{7}, Name: "+{0} Life after each Demon Kill"},
	// Unknown property, shows up on Swordback Hold Spiked Shield.
	140: {Bits: []uint{7}, Name: "Unknown"},
	141: {Bits: []uint{7}, Name: "{0}% Deadly Strike"},
	142: {Bits: []uint{7}, Name: "Fire Absorb {0}%"},
	143: {Bits: []uint{7}, Name: "+{0} Fire Absorb"},
	144: {Bits: []uint{7}, Name: "Lightning Absorb {0}%"},
	145: {Bits: []uint{7}, Name: "+{0} Lightning Absorb"},
	146: {Bits: []uint{7}, Name: "Magic Absorb {0}%"},
	147: {Bits: []uint{7}, Name: "+{0} Magic Absorb"},
	148: {Bits: []uint{7}, Name: "Cold Absorb {0}%"},
	149: {Bits: []uint{7}, Name: "+{0} Cold Absorb"},
	150: {Bits: []uint{7}, Name: "Slows Target by {0}%"},
	151: {Bits: []uint{9, 5}, Name: "Level +{0} {1} When Equipped"},
	152: {Bits: []uint{1}, Name: "Indestructible"},
	153: {Bits: []uint{1}, Name: "Cannot Be Frozen"},
	154: {Bits: []uint{7}, Bias: 20, Name: "{0}% Slower Stamina Drain"},
	155: {Bits: []uint{10, 7}, Name: "{0}% Chance to Reanimate Target"},
	156: {Bits: []uint{7}, Name: "Piercing Attack"},
	157: {Bits: []uint{7}, Name: "Fires Magic Arrows"},
	158: {Bits: []uint{7}, Name: "Fires Explosive Arrows or Bolts"},
	159: {Bits: []uint{6}, Name: "+{0} to Minimum Throw Damage"},
	160: {Bits: []uint{7}, Name: "+{0} to Maximum Throw Damage"},
	179: {Bits: []uint{3}, Name: "+{0} to Druid Skill Levels"},
	180: {Bits: []uint{3}, Name: "+{0} to Assassin Skill Levels"},

	// Ok so get this, this is quite complicated, the id 188 is for items with
	// + x to a certain skill tree, e.g. 1 + to defensive auras (paladin).
	//
	// So here's how it works, the field is 19 bits long, here's the bits for
	// the defensive auras skiller.
	//
	// 001             0000000000             011              010
	//  ^                  ^                   ^                ^
	// levels        unknown padding        class id       skill tree offset
	//
	// So in the above example, the first 3 bits 001 are the + levels (1), we'll
	// ignore the padding, the second interesting set of 3 bits is the class id.
	// Refer to the class.go for class ids, but paladin is 011 (3), and the
	// last 3 bits 010 (2) is the offset from the start of the class skill tree.
	// Refer to skills.go to find the different tree offsets. Paladin offset is
	// 9. So remember the last 3 bits 010 (2), that means the skill tree is
	// 9 + 2 = 11, aka the defensive auras tree.
	//
	// When reading the values, remember the bits are read from the right,
	// so the values will be [2 3 1], offset 2, class id 3, 1 + to skills.
	188: {Bits: []uint{3, 13, 3}, Name: "+{2} to {0} Skills ({1} only)"},

	189: {Bits: []uint{10, 9}, Name: "+{0} to {1} Skills (char_class Only)"},
	190: {Bits: []uint{10, 9}, Name: "+{0} to {1} Skills (char_class Only)"},
	191: {Bits: []uint{10, 9}, Name: "+{0} to {1} Skills (char_class Only)"},
	192: {Bits: []uint{10, 9}, Name: "+{0} to {1} Skills (char_class Only)"},
	193: {Bits: []uint{10, 9}, Name: "+{0} to {1} Skills (char_class Only)"},

	194: {Bits: []uint{4}, Name: "Adds {0} extra sockets to the item"},

	// Order is spell id, level, % chance.
	195: {Bits: []uint{6, 10, 7}, Name: "{2}% Chance to Cast Level {0} {1} When you die"},
	196: {Bits: []uint{6, 10, 7}, Name: "{2}% Chance to Cast Level {0} {1} When you die"},
	197: {Bits: []uint{6, 10, 7}, Name: "{2}% Chance to Cast Level {0} {1} When you die"},

	// Order is spell id, level, % chance.
	198: {Bits: []uint{6, 10, 7}, Name: "{2}% Chance to Cast Level {0} {1} On Striking"},
	199: {Bits: []uint{6, 10, 7}, Name: "{2}% Chance to Cast Level {0} {1} On Striking"},
	200: {Bits: []uint{6, 10, 7}, Name: "{2}% Chance to Cast Level {0} {1} On Striking"},

	// Order is spell id, level, % chance.
	201: {Bits: []uint{6, 10, 7}, Name: "{2}% Chance to Cast Level {0} {1} When Struck"},
	202: {Bits: []uint{6, 10, 7}, Name: "{2}% Chance to Cast Level {0} {1} When Struck"},
	203: {Bits: []uint{6, 10, 7}, Name: "{2}% Chance to Cast Level {0} {1} When Struck"},

	// First value selects the spell id, second value is level, third is remaining charges
	// and the last is the total number of charges.
	204: {Bits: []uint{6, 10, 8, 8}, Name: "Level {0} {1} ({2}/{3} Charges)"},
	205: {Bits: []uint{6, 10, 8, 8}, Name: "Level {0} {1} ({2}/{3} Charges)"},
	206: {Bits: []uint{6, 10, 8, 8}, Name: "Level {0} {1} ({2}/{3} Charges)"},
	207: {Bits: []uint{6, 10, 8, 8}, Name: "Level {0} {1} ({2}/{3} Charges)"},
	208: {Bits: []uint{6, 10, 8, 8}, Name: "Level {0} {1} ({2}/{3} Charges)"},
	209: {Bits: []uint{6, 10, 8, 8}, Name: "Level {0} {1} ({2}/{3} Charges)"},
	210: {Bits: []uint{6, 10, 8, 8}, Name: "Level {0} {1} ({2}/{3} Charges)"},
	211: {Bits: []uint{6, 10, 8, 8}, Name: "Level {0} {1} ({2}/{3} Charges)"},
	212: {Bits: []uint{6, 10, 8, 8}, Name: "Level {0} {1} ({2}/{3} Charges)"},
	213: {Bits: []uint{6, 10, 8, 8}, Name: "Level {0} {1} ({2}/{3} Charges)"},

	// All values based on character level are stored in eights, so take
	// the number divide by 8 and multiply by the character level and round down.
	// Or, just do (value * 0.125)% per level.
	214: {Bits: []uint{6}, Name: "+{0} to Defense (Based on Character Level)"},
	215: {Bits: []uint{6}, Name: "{0}% Enhanced Defense (Based on Character Level)"},
	216: {Bits: []uint{6}, Name: "+{0} to Life (Based on Character Level)"},
	217: {Bits: []uint{6}, Name: "+{0} to Mana (Based on Character Level)"},
	218: {Bits: []uint{6}, Name: "+{0} to Maximum Damage (Based on Character Level)"},
	219: {Bits: []uint{6}, Name: "{0}% Enhanced Maximum Damage (Based on Character Level)"},
	220: {Bits: []uint{6}, Name: "+{0} to Strength (Based on Character Level)"},
	221: {Bits: []uint{6}, Name: "+{0} to Dexterity (Based on Character Level)"},
	222: {Bits: []uint{6}, Name: "+{0} to Energy (Based on Character Level)"},
	223: {Bits: []uint{6}, Name: "+{0} to Vitality (Based on Character Level)"},
	224: {Bits: []uint{6}, Name: "+{0} to Attack Rating (Based on Character Level)"},
	225: {Bits: []uint{6}, Name: "{0}% Bonus to Attack Rating (Based on Character Level)"},
	226: {Bits: []uint{6}, Name: "+{0} Cold Damage (Based on Character Level)"},
	227: {Bits: []uint{6}, Name: "+{0} Fire Damage (Based on Character Level)"},
	228: {Bits: []uint{6}, Name: "+{0} Lightning Damage (Based on Character Level)"},
	229: {Bits: []uint{6}, Name: "+{0} Poison Damage (Based on Character Level)"},
	230: {Bits: []uint{6}, Name: "Cold Resist +{0}% (Based on Character Level)"},
	231: {Bits: []uint{6}, Name: "Fire Resist +{0}% (Based on Character Level)"},
	232: {Bits: []uint{6}, Name: "Lightning Resist +{0}% (Based on Character Level)"},
	233: {Bits: []uint{6}, Name: "Poison Resist +{0}% (Based on Character Level)"},
	234: {Bits: []uint{6}, Name: "+{0} Cold Absorb (Based on Character Level)"},
	235: {Bits: []uint{6}, Name: "+{0} Fire Absorb (Based on Character Level)"},
	236: {Bits: []uint{6}, Name: "+{0} Lightning Absorb (Based on Character Level)"},
	237: {Bits: []uint{6}, Name: "{0} Poison Absorb (Based on Character Level)"},
	238: {Bits: []uint{5}, Name: "Attacker Takes Damage of {0} (Based on Character Level)"},
	239: {Bits: []uint{6}, Name: "{0}% Extra Gold from Monsters (Based on Character Level)"},
	240: {Bits: []uint{6}, Name: "{0}% Better Chance of Getting Magic Items (Based on Character Level)"},
	241: {Bits: []uint{6}, Name: "Heal Stamina Plus {0}% (Based on Character Level)"},
	243: {Bits: []uint{6}, Name: "{0}% Damage to Demons (Based on Character Level)"},
	244: {Bits: []uint{6}, Name: "{0}% Damage to Undead (Based on Character Level)"},
	245: {Bits: []uint{6}, Name: "+{0} to Attack Rating against Demons (Based on Character Level)"},
	246: {Bits: []uint{6}, Name: "+{0} to Attack Rating against Undead (Based on Character Level)"},
	247: {Bits: []uint{6}, Name: "{0}% Chance of Crushing Blow (Based on Character Level)"},
	248: {Bits: []uint{6}, Name: "{0}% Chance of Open Wounds (Based on Character Level)"},
	249: {Bits: []uint{6}, Name: "+{0} Kick Damage (Based on Character Level)"},
	250: {Bits: []uint{6}, Name: "{0}% to Deadly Strike (Based on Character Level)"},

	// The value of the data field is not actually a time period, but a frequency in terms
	// of the number of times durability is repaired over a period of 100 seconds.
	// For example, if the value is 5, then this property repairs 1 durability in 100 / 5 = 20 seconds.
	252: {Bits: []uint{5}, Name: "Repairs 1 Durability in {0} Seconds"},

	// As in the previous property, the value of the data field is a frequency in terms of the number
	// replenished over a period of 100 seconds. For example if the value is 4, then this property
	// replenishes 1 item in 100 / 4 = 25 seconds.
	253: {Bits: []uint{6}, Name: "Replenishes Quantity"},

	// Number of additional items beyond the base limit, for example if the base
	// is 50 and additional is 30, then the total is 50 + 30.
	254: {Bits: []uint{8}, Name: "Increased Stack Size"},

	// IDs 268 - 303 are some weird values that were never used in the actual game.
	// These values change depending on the time of day in the game.
	// The format of the bit fields are the same in all cases, the first 2 bits
	// specifies the the of time when the value is at its maximum.
	//
	// The second and third are respectively the minimum and maximum values of the property.
	// The maximum value at the time specified and the minimum at the opposite.

	329: {Bits: []uint{9}, Bias: 50, Name: "{0}% To Fire Skill Damage"},
	330: {Bits: []uint{9}, Bias: 50, Name: "{0}% To Lightning Skill Damage"},
	331: {Bits: []uint{9}, Bias: 50, Name: "{0}% To Cold Skill Damage"},
	332: {Bits: []uint{9}, Bias: 50, Name: "{0}% To Poison Skill Damage"},
	333: {Bits: []uint{8}, Name: "-{0}% To Enemy Fire Resistance"},
	334: {Bits: []uint{8}, Name: "-{0}% To Enemy Lightning Resistance"},
	335: {Bits: []uint{8}, Name: "-{0}% To Enemy Cold Resistance"},
	336: {Bits: []uint{8}, Name: "-{0}% To Enemy Poison Resistance"},
}

// Each set item has 5 bits of data containing the number of set lists follow
// the magical attributes list, this map tells us how many lists to read
// depending on the value given from the 5 bits. A number of 0-5 set lists.
var setListMap = map[uint64]uint64{
	0:  0,
	1:  1,
	3:  2,
	7:  3,
	15: 4,
	31: 5,
}

// All item types that contain the quantity bits will exist in here,
// we'll use this when reading items to make sure we only read quantity bits
// when they exist, or we'll ruin the rest of the bit offsets for the item.
var quantityMap = map[string]bool{
	"tbk": true,
	"ibk": true,
	"key": true,
	"ama": true,
	"tsp": true,
}

// Items that are tomes contain 5 extra bits, so we need to keep track of what
// items are tomes, and read the bits accordingly.
var tomeMap = map[string]bool{
	"tbk": true,
	"ibk": true,
}
