package d2s

var socketablesWeapons = map[string][]magicAttribute{
	"r01": []magicAttribute{magicAttribute{ID: 19, Name: "+{0} to Attack rating", Values: []int64{50}}, magicAttribute{ID: 89, Name: "+{0} to Light Radius", Values: []int64{1}}},
	"r02": []magicAttribute{magicAttribute{ID: 122, Name: "+{0}% Damage to Undead", Values: []int64{75}}, magicAttribute{ID: 124, Name: "+{0} to Attack Rating against Undead", Values: []int64{50}}},
	"r03": []magicAttribute{magicAttribute{ID: 138, Name: "+{0} to Mana After Each Kill", Values: []int64{2}}},
	"r04": []magicAttribute{magicAttribute{ID: 81, Name: "Knockback", Values: []int64{1}}},
	"r05": []magicAttribute{magicAttribute{ID: 116, Name: "{0}% Target Defense", Values: []int64{-25}}},
	"r06": []magicAttribute{magicAttribute{ID: 22, Name: "+{0} to Maximum 1-handed damage", Values: []int64{9}}, magicAttribute{ID: 24, Name: "+{0} to Maximum 2-handed damage", Values: []int64{9}}},
	"r07": []magicAttribute{magicAttribute{ID: 57, Name: "Adds {0}-{1} Poison Damage over {2} Seconds", Values: []int64{154, 154, 125}}},
	"r08": []magicAttribute{magicAttribute{ID: 48, Name: "Adds {0}-{1} Fire Damage", Values: []int64{5, 30}}},
	"r09": []magicAttribute{magicAttribute{ID: 50, Name: "Adds {0}-{1} Lightning Damage", Values: []int64{1, 50}}},
	"r10": []magicAttribute{magicAttribute{ID: 54, Name: "Adds {0}-{1} Cold Damage", Values: []int64{3, 14, 75}}},
	"r11": []magicAttribute{magicAttribute{ID: 60, Name: "{0}% Life stolen per hit", Values: []int64{7}}},
	"r12": []magicAttribute{magicAttribute{ID: 21, Name: "+{0} to Minimum 1-handed damage", Values: []int64{9}}, magicAttribute{ID: 23, Name: "+{0} to Minimum 2-handed damage", Values: []int64{9}}},
	"r13": []magicAttribute{magicAttribute{ID: 93, Name: "{0}% Increased Attack Speed", Values: []int64{20}}},
	"r14": []magicAttribute{magicAttribute{ID: 112, Name: "Hit Causes Monsters to Flee {0}%", Values: []int64{25}}},
	"r15": []magicAttribute{magicAttribute{ID: 91, Name: "Requirements {0}%", Values: []int64{-20}}},
	"r16": []magicAttribute{magicAttribute{ID: 3, Name: "+{0} to Vitality", Values: []int64{10}}},
	"r17": []magicAttribute{magicAttribute{ID: 1, Name: "+{0} to Energy", Values: []int64{10}}},
	"r18": []magicAttribute{magicAttribute{ID: 2, Name: "+{0} to Dexterity", Values: []int64{10}}},
	"r19": []magicAttribute{magicAttribute{ID: 0, Name: "+{0} to Strength", Values: []int64{10}}},
	"r20": []magicAttribute{magicAttribute{ID: 79, Name: "{0}% Extra Gold from Monsters", Values: []int64{75}}},
	"r21": []magicAttribute{magicAttribute{ID: 121, Name: "+{0}% Damage to Demons", Values: []int64{75}}, magicAttribute{ID: 123, Name: "+{0} to Attack Rating against Demons", Values: []int64{100}}},
}

var socketablesArmor = map[string][]magicAttribute{
	"r01": []magicAttribute{magicAttribute{ID: 31, Name: "+{0} Defense", Values: []int64{15}}, magicAttribute{ID: 89, Name: "+{0} to Light Radius", Values: []int64{1}}},
	"r02": []magicAttribute{magicAttribute{ID: 154, Name: "{0}% Slower Stamina Drain", Values: []int64{15}}},
	"r03": []magicAttribute{magicAttribute{ID: 138, Name: "+{0} to Mana After Each Kill", Values: []int64{2}}},
	"r04": []magicAttribute{magicAttribute{ID: 32, Name: "+{0} vs. Missile", Values: []int64{30}}},
	"r05": []magicAttribute{magicAttribute{ID: 27, Name: "Regenerate Mana {0}%", Values: []int64{15}}},
	"r06": []magicAttribute{magicAttribute{ID: 114, Name: "{0}% Damage Taken Goes to Mana", Values: []int64{15}}},
	"r07": []magicAttribute{magicAttribute{ID: 45, Name: "Poison Resist +{0}%", Values: []int64{35}}},
	"r08": []magicAttribute{magicAttribute{ID: 39, Name: "Fire Resist +{0}%", Values: []int64{35}}},
	"r09": []magicAttribute{magicAttribute{ID: 41, Name: "Lightning Resist +{0}%", Values: []int64{35}}},
	"r10": []magicAttribute{magicAttribute{ID: 43, Name: "Cold Resist +{0}%", Values: []int64{35}}},
	"r11": []magicAttribute{magicAttribute{ID: 78, Name: "Attacker Takes Damage of {0}", Values: []int64{14}}},
	"r12": []magicAttribute{magicAttribute{ID: 34, Name: "Damage Reduced by {0}", Values: []int64{7}}},
	"r13": []magicAttribute{magicAttribute{ID: 99, Name: "{0}% Faster Hit Recovery", Values: []int64{20}}},
	"r14": []magicAttribute{magicAttribute{ID: 74, Name: "Replenish Life +{0}", Values: []int64{7}}},
	"r15": []magicAttribute{magicAttribute{ID: 91, Name: "Requirements {0}%", Values: []int64{-15}}},
	"r16": []magicAttribute{magicAttribute{ID: 3, Name: "+{0} to Vitality", Values: []int64{10}}},
	"r17": []magicAttribute{magicAttribute{ID: 1, Name: "+{0} to Energy", Values: []int64{10}}},
	"r18": []magicAttribute{magicAttribute{ID: 2, Name: "+{0} to Dexterity", Values: []int64{10}}},
	"r19": []magicAttribute{magicAttribute{ID: 0, Name: "+{0} to Strength", Values: []int64{10}}},
	"r20": []magicAttribute{magicAttribute{ID: 79, Name: "{0}% Extra Gold from Monsters", Values: []int64{50}}},
	"r21": []magicAttribute{magicAttribute{ID: 16, Name: "+{0}% Enhanced Defense", Values: []int64{30}}},
}

var socketablesShields = map[string][]magicAttribute{
	"r01": []magicAttribute{magicAttribute{ID: 31, Name: "+{0} Defense", Values: []int64{15}}, magicAttribute{ID: 89, Name: "+{0} to Light Radius", Values: []int64{1}}},
	"r02": []magicAttribute{magicAttribute{ID: 20, Name: "+{0}% Increased chance of blocking", Values: []int64{7}}},
	"r03": []magicAttribute{magicAttribute{ID: 138, Name: "+{0} to Mana After Each Kill", Values: []int64{2}}},
	"r04": []magicAttribute{magicAttribute{ID: 32, Name: "+{0} vs. Missile", Values: []int64{30}}},
	"r05": []magicAttribute{magicAttribute{ID: 27, Name: "Regenerate Mana {0}%", Values: []int64{15}}},
	"r06": []magicAttribute{magicAttribute{ID: 114, Name: "{0}% Damage Taken Goes to Mana", Values: []int64{15}}},
	"r07": []magicAttribute{magicAttribute{ID: 45, Name: "Poison Resist +{0}%", Values: []int64{35}}},
	"r08": []magicAttribute{magicAttribute{ID: 39, Name: "Fire Resist +{0}%", Values: []int64{35}}},
	"r09": []magicAttribute{magicAttribute{ID: 41, Name: "Lightning Resist +{0}%", Values: []int64{35}}},
	"r10": []magicAttribute{magicAttribute{ID: 43, Name: "Cold Resist +{0}%", Values: []int64{35}}},
	"r11": []magicAttribute{magicAttribute{ID: 78, Name: "Attacker Takes Damage of {0}", Values: []int64{14}}},
	"r12": []magicAttribute{magicAttribute{ID: 34, Name: "Damage Reduced by {0}", Values: []int64{7}}},
	"r13": []magicAttribute{magicAttribute{ID: 102, Name: "{0}% Faster Block Rate", Values: []int64{20}}},
	"r14": []magicAttribute{magicAttribute{ID: 74, Name: "Replenish Life +{0}", Values: []int64{7}}},
	"r15": []magicAttribute{magicAttribute{ID: 91, Name: "Requirements {0}%", Values: []int64{-15}}},
	"r16": []magicAttribute{magicAttribute{ID: 3, Name: "+{0} to Vitality", Values: []int64{10}}},
	"r17": []magicAttribute{magicAttribute{ID: 1, Name: "+{0} to Energy", Values: []int64{10}}},
	"r18": []magicAttribute{magicAttribute{ID: 2, Name: "+{0} to Dexterity", Values: []int64{10}}},
	"r19": []magicAttribute{magicAttribute{ID: 0, Name: "+{0} to Strength", Values: []int64{10}}},
	"r20": []magicAttribute{magicAttribute{ID: 79, Name: "{0}% Extra Gold from Monsters", Values: []int64{50}}},
	"r21": []magicAttribute{magicAttribute{ID: 16, Name: "+{0}% Enhanced Defense", Values: []int64{30}}},
}
